pub const VmError = error{
    LuaError,
    TypeMismatch,
    StackOverflow,
    NotCallable,
    OutOfMemory,
    ParseError,
    UndefinedVariable,
    BreakOutsideLoop,
    ReturnOutsideFunction,
    ArityMismatch,
    InvalidNumber,
    InvalidEscape,
    UnterminatedString,
    UnexpectedEof,
    UnexpectedToken,
};
